### ISSUE TITLE
The README is missing a backstory for the lib name

### ISSUE THREAD

**Issue by AliSoftware** [RuiAAPeres/Tangerine#2]
The very first and most important thing I wanted to know first time I saw this library was obviously "but why is it named Tangerine?"

I mean I'm sure it's not just random and there's a clever play on words or backstory somewhere there and I think it's top priority to include it in the README as it's the first thing people are gonna wonder about it, and that's probably gonna prevent them to sleep, or bug them enough to the point that they're gonna be blocked by that question and not gonna look further into what the lib is able to do, so I think it's a very important issue to fix.

**Comment by RuiAAPeres** [comment]
Well, I started this repo with the goal of creating a Hacker news client. Hacker news is also known as the orange website, and as such I came up with Tangerine 🍊. After creating the repository, I came to the conclusion that it would be too much effort and given that some people wanted something like this, I decided to take the easier path. 😂 

![](https://media3.giphy.com/media/TITNEEVy0Q8aXmAAdF/giphy.gif)

**Comment by AliSoftware** [comment]
See? I knew there was a backstory
